# Generated by Django 2.1.3 on 2019-05-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20190520_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagef',
            new_name='image',
        ),
    ]
